# environments:
#   default:
#     values:
#       - secrets/aws-creds.yaml
# 
# ---

repositories:
  - name: external-secrets
    url: https://charts.external-secrets.io 

  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

  - name: cert-manager
    url: https://charts.jetstack.io

  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns

 
 
releases:
  - name: external-secrets
    namespace: external-secrets
    createNamespace: true
    chart: external-secrets/external-secrets
    version: "v0.17.0"
    labels:
      phase: eso
      crd: true

    set: 
    - name: installCRDs
      value: "true"
 
  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: "4.12.2"  
    labels:
      phase: ino
      crd: true
    set:
    - name: controller.progressDeadlineSeconds
      value: 600
# 
#   - name: cert-manager
#     namespace: cert-manager
#     createNamespace: true
#     chart: jetstack/cert-manager
#     version: "v1.17"  
#     labels:
#       phase: cmo
#     set:
#     - name: crds.enabled
#       value: "true"
# 
#   - name: external-dns
#     namespace: external-dns
#     createNamespace: true
#     chart: external-dns/external-dns
#     version: 1.16.1
#     labels:
#       phase: edo
#     values:
#     - ../helm-charts-stable/external-dns/values.yaml

  - name: aws-secrets-wrapper
    namespace: external-secrets
    chart: ./charts/aws-secret-wrapper
    labels:
      phase: asw
      helm: true
    secrets:
      - secrets/aws-creds.yaml
    needs:
      - external-secrets
