---
# Source: aws-secret-wrapper/templates/aws-ssm-secret.yaml
# This file is part of the AWS Secret Wrapper Helm Chart.
# It deploys a Kubernetes Secret containing AWS credentials for accessing AWS Parameter Store.
# Secrets used in this chart encoded by helm secrets plugin with AWS KMS keys
# path to original secrets are secrets/aws-creds.yaml (encrypted)

apiVersion: v1
kind: Secret
metadata:
  name: aws-ssm-secret
  namespace: external-secrets
type: Opaque
data:
  access-key: QUtJQVpZMjM2R0hWRDZGVVhQUzY=
  secret-access-key: YkZrcUd5Y2VmMHNrV29OckhURTBMSUhiaVBtcGszNnZrRzB1MFFOTw==
---
# Source: aws-secret-wrapper/templates/cmo-cluster-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    # Staging server for testing
    # server: https://acme-staging-v02.api.letsencrypt.org/directory

    server: https://acme-v02.api.letsencrypt.org/directory
    email: yourtaev@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer
    solvers:
    - dns01:
        route53:
          region: "eu-central-1" 
          accessKeyIDSecretRef:
            name: cert-manager-aws-key
            key: access-key-id
          secretAccessKeySecretRef:
            name: cert-manager-aws-key
            key: secret-access-key
---
# Source: aws-secret-wrapper/templates/eso-cluster-secret-store.yaml
# Deploy a ClusterSecretStore for AWS Parameter Store
# This ClusterSecretStore will be used by the External Secrets Operator to fetch secrets from AWS Parameter Store
# and make them available in the Kubernetes cluster.

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-cluster-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: "eu-central-1"
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: external-secrets
            name: aws-ssm-secret
            key: access-key
          secretAccessKeySecretRef:
            namespace: external-secrets
            name: aws-ssm-secret
            key: secret-access-key
---
# Source: aws-secret-wrapper/templates/eso-cert-manager.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-aws-key
  namespace:  cert-manager  

spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore  # Use 'SecretStore' if it's namespace-scoped
    name: aws-cluster-parameter-store
  target:
    name: cert-manager-aws-key # Name of the Kubernetes Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: access-key-id  # Key in the Kubernetes Secret
      remoteRef:
        key: /hetzner/k8s/cert-manager-user/access_key  # Path in AWS Parameter Store
    - secretKey: secret-access-key  # Key in the Kubernetes Secret
      remoteRef:
        key: /hetzner/k8s/cert-manager-user/secret_key  # Path in AWS Parameter Store
---
# Source: aws-secret-wrapper/templates/eso-external-dns.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-aws-key
  namespace: external-dns  # Ensure this namespace exists or change it to your desired namespace

spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore  # Use 'SecretStore' if it's namespace-scoped
    name: aws-cluster-parameter-store
  target:
    name: external-dns-aws-key # Name of the Kubernetes Secret to be created
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        my_credentials: |
          [default]
          aws_access_key_id     = "{{ .aws_access_key_id }}"
          aws_secret_access_key = "{{ .aws_secret_access_key }}"
          region                = us-east-1
  data:
    - secretKey: aws_access_key_id  # Key in the Kubernetes Secret
      remoteRef:
        key: /hetzner/k8s/external-dns-user/access_key  # Path in AWS Parameter Store
    - secretKey: aws_secret_access_key  # Key in the Kubernetes Secret
      remoteRef:
        key: /hetzner/k8s/external-dns-user/secret_key  # Path in AWS Parameter Store

