# This file is part of the AWS Secret Wrapper Helm Chart.
# It deploys a Kubernetes Secret containing AWS credentials for accessing AWS Parameter Store.
# Secrets used in this chart encoded by helm secrets plugin with AWS KMS keys
# path to original secrets are secrets/aws-creds.yaml (encrypted)

apiVersion: v1
kind: Secret
metadata:
  name: aws-ssm-secret
  namespace: external-secrets
type: Opaque
data:
  access-key: {{ .Values.aws_access_key_id | b64enc }}
  secret-access-key: {{ .Values.aws_secret_access_key | b64enc }}
