apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    # Staging server for testing
    # server: https://acme-staging-v02.api.letsencrypt.org/directory

    server: https://acme-v02.api.letsencrypt.org/directory
    email: yourtaev@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer
    solvers:
    - dns01:
        route53:
          region: "eu-central-1" 
          accessKeyIDSecretRef:
            name: cert-manager-aws-key
            key: access-key-id
          secretAccessKeySecretRef:
            name: cert-manager-aws-key
            key: secret-access-key