# Deploy a ClusterSecretStore for AWS Parameter Store
# This ClusterSecretStore will be used by the External Secrets Operator to fetch secrets from AWS Parameter Store
# and make them available in the Kubernetes cluster.

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-cluster-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: "eu-central-1"
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: external-secrets
            name: aws-ssm-secret
            key: access-key
          secretAccessKeySecretRef:
            namespace: external-secrets
            name: aws-ssm-secret
            key: secret-access-key
